### PR TITLE
Db rewrite

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by PEMapModder** [comment]
Vote: Merge this?
- [x] @PEMapModder
- [x] @iksaku
- [x] @DinoKill
- [x] @ijoshuahd
- [ ] @LukeDarling
- [x] @Falkirks
- [x] @64FF00

Check your own box

**Comment by iksaku** [comment]
Btw: can you help me to make HealthBar support DBs? Thanks! :D

**Comment by PEMapModder** [comment]
What databases?

**Comment by iksaku** [comment]
Ooops! I mean MoreHealth (not HealthBar) and any easy to learn database, SQLite, MySQL, anyone :P it doesn't matter

**Comment by PEMapModder** [comment]
The language reference at the SQLite official site is fun to learn with :)

**Comment by iksaku** [comment]
Link? Pleas :P

**Comment by PEMapModder** [comment]
Search "SQLite3 create table" on Google. Also, look at humerus's thread on PocketMine forums.

**Comment by iJoshuaHD** [comment]
how come u guys have the all the time in the world? :(

**Comment by PEMapModder** [comment]
?

**Comment by iksaku** [comment]
Because I'm on vacations... Just for school xD and from 4-9pm I'm training :) (morning now for me xD)

**Comment by iksaku** [comment]
@PEMapModder wow! It seems easy to learn SQLite... Humerus example make it easier to understand :D

**Comment by PEMapModder** [comment]
:)

**Comment by PEMapModder** [comment]
Let's wait for one more person to vote. @Falkirks @LukeDarling @DinoKill @64FF00?

**Comment by iJoshuaHD** [comment]
majority had checked their own boxes now merge it :P

**Comment by iJoshuaHD** [comment]
just merge it already :P all against one has nothing to do with it unless he is Hulk.

**Comment by PEMapModder** [comment]
Lol

**Pull request merged**
