### PR TITLE
added autoclaim subcommand

### PR DESCRIPTION
**Pull request by LukeDarling**

### CODE REVIEW

**Comment by PEMapModder** [comment]
I'll wait you add the actual subcommand. Also, please order that part of permissions in alphabetical order if possible.

**Comment by PEMapModder** [comment]
What?

**Comment by LukeDarling** [comment]
Hmm?

**Comment by PEMapModder** [comment]
Why did you delete it?

**Comment by PEMapModder** [comment]
@LukeDarling talk on IRC.

**Comment by LukeDarling** [comment]
Because I don't know how to edit branches. :P And ok.

**Comment by PEMapModder** [comment]
https://github.com/lukedarling/PocketFactions/tree/patch-1

**Pull request closed without merging**
